Repository basedosdados/website, pull requests merged in 2022-10, with the labels that each got.

#482 Feat/case studies
  next/components/atoms/Display.js
  next/components/molecules/DataInformationQuery.js
  next/components/molecules/DisclaimerBox.js
  next/components/molecules/Footer.js
  next/components/molecules/Menu.js
  next/components/molecules/MenuDropdown.js
  next/components/organisms/Database.js
  next/components/organisms/DatabaseCard.js
  next/pages/contato.js
  next/pages/estudos-de-caso/[id].js
  next/pages/estudos-de-caso/content.js
  next/pages/index.js
  next/pages/perguntas-frequentes/content.js
  next/pages/perguntas-frequentes/index.js
  next/pages/quem-somos.js
  next/pages/transparencia.js
  next/public/img/icons/calendarIcon.js
  next/public/img/icons/copyIcon.js
  next/styles/caseStudies.module.css
  next/styles/faq.module.css
Labels: Type: Feature 🚀, Topic: Front-end 🎨

#486 Staging
  next/components/atoms/Display.js
  next/components/molecules/DataInformationQuery.js
  next/components/molecules/DisclaimerBox.js
  next/components/molecules/Footer.js
  next/components/molecules/Menu.js
  next/components/molecules/MenuDropdown.js
  next/components/organisms/Database.js
  next/components/organisms/DatabaseCard.js
  next/content/FAQ.js
  next/content/caseStudies.js
  next/pages/contato.js
  next/pages/estudos-de-caso/[id].js
  next/pages/index.js
  next/pages/perguntas-frequentes/index.js
  next/pages/quem-somos.js
  next/pages/transparencia.js
  next/public/img/icons/calendarIcon.js
  next/public/img/icons/copyIcon.js
  next/styles/caseStudies.module.css
  next/styles/faq.module.css
Labels: Type: Feature 🚀, Topic: Front-end 🎨

#488 ajust page caseStudies
  next/content/caseStudies.js
  next/pages/estudos-de-caso/[id].js
Labels: Type: Feature 🚀, Topic: Front-end 🎨

#489 Staging
  next/content/caseStudies.js
  next/pages/estudos-de-caso/[id].js
Labels: Type: Feature 🚀, Topic: Front-end 🎨

#490 add thumbnail in case stuides
  next/content/caseStudies.js
  next/pages/estudos-de-caso/[id].js
Labels: Type: Feature 🚀, Topic: Front-end 🎨

#487 fix temporal coverage
  next/components/organisms/BdmTablePage.js
  next/utils.js
Labels: Type: Bug 🐛, Topic: Front-end 🎨

#491 Staging
  next/components/organisms/BdmTablePage.js
  next/content/caseStudies.js
  next/pages/estudos-de-caso/[id].js
  next/utils.js
Labels: Type: Feature 🚀, Topic: Front-end 🎨

#493 Ajust thumbnail case studies
  next/pages/estudos-de-caso/[id].js
Labels: Topic: Front-end 🎨

#494 Chore/thumbnail
  next/pages/estudos-de-caso/[id].js
Labels: Topic: Front-end 🎨

#495 Staging
  next/content/caseStudies.js
  next/pages/estudos-de-caso/[id].js
  next/styles/caseStudies.module.css
Labels: Topic: Front-end 🎨

#497 Feat/measurement unit latex
  next/components/molecules/ColumnDatasets.js
  next/components/molecules/ExpandableTable.js
  next/package-lock.json
  next/package.json
  next/yarn.lock
Labels: Type: Feature 🚀, Topic: Front-end 🎨

#502 Remove datasets ajust
  next/components/organisms/MetadataPage.js
Labels: Type: Bug 🐛

#503 Fix link download of datasets
  next/components/molecules/DataInformationQuery.js
  next/components/organisms/BdmTablePage.js
  next/components/organisms/MetadataPage.js
  next/pages/index.js
Labels: Topic: Front-end 🎨

#500 [infra] fix gcp project endpoint analytics
  ckanext-basedosdados/ckanext/basedosdados/actions/utils.py
  next/components/molecules/DataInformationQuery.js
  next/components/organisms/BdmTablePage.js
  next/components/organisms/MetadataPage.js
  next/pages/index.js
Labels: Type: Feature 🚀, Topic: Front-end 🎨

#505 Email in bdmtable
  next/components/organisms/BdmTablePage.js
Labels: Type: Feature 🚀

#506 Staging
  .github/workflows/cd.yml
  ckanext-basedosdados/ckanext/basedosdados/actions/utils.py
  next/components/organisms/BdmTablePage.js
Labels: Type: Feature 🚀, Topic: Front-end 🎨

#507 change published and data_cleaned, Equipe Dados
  next/components/organisms/BdmTablePage.js
Labels: Topic: Front-end 🎨

#508 Staging
  next/components/organisms/BdmTablePage.js
Labels: Type: Feature 🚀, Topic: Front-end 🎨
