Repository basedosdados/website, pull requests merged in 2022-01, with the labels that each got.

#192 Measurement additions
  ckanext-basedosdados/ckanext/basedosdados/validator/available_options/measurement_unit.py
Labels: backend

#193 Update code sample to R package v0.1.0
  next/components/organisms/BdmTablePage.js
Labels: frontend

#212 infra: revisão de metadados
  ckanext-basedosdados/ckanext/basedosdados/actions/get.py
  ckanext-basedosdados/ckanext/basedosdados/validator/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/available_options/bigquery_type.py
  ckanext-basedosdados/ckanext/basedosdados/validator/available_options/entity.py
  ckanext-basedosdados/ckanext/basedosdados/validator/available_options/temporal_coverage.py
  ckanext-basedosdados/ckanext/basedosdados/validator/packages/dataset/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/packages/dataset/fields_definitions.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/column/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/column/fields_definitions.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/dictionary/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/table/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/table/fields_definitions.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/external_link/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/external_link/fields_definitions.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/information_request/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/information_request/fields_definitions.py
  configs/ckan.ini
  next/components/organisms/BdmTablePage.js
  next/components/organisms/Database.js
  next/components/organisms/ExternalLinkPage.js
  next/components/organisms/MetadataPage.js
  next/pages/api/schemas.js
  next/pages/dataset/[dataset].js
  next/pages/dataset/index.js
  utils/migration/migration-metadata-upgrade.ipynb
Labels: Topic: Metadata 📝, Topic: Front-end 🎨

#225 More changes to metadata
  ckanext-basedosdados/ckanext/basedosdados/actions/get.py
  ckanext-basedosdados/ckanext/basedosdados/validator/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/available_options/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/available_options/license.py
  ckanext-basedosdados/ckanext/basedosdados/validator/available_options/measurement_unit.py
  ckanext-basedosdados/ckanext/basedosdados/validator/available_options/spatial_coverage.py
  ckanext-basedosdados/ckanext/basedosdados/validator/packages/ckan_default/package.py
  ckanext-basedosdados/ckanext/basedosdados/validator/packages/dataset/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/packages/dataset/fields_definitions.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/column/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/column/fields_definitions.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/table/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/table/fields_definitions.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/external_link/__init__.py
  ckanext-basedosdados/ckanext/basedosdados/validator/resources/information_request/__init__.py
  next/pages/api/schemas.js
  next/pages/dataset/index.js
  utils/migration/2022-01-27-migration-metadata-upgrade.ipynb
  utils/migration/migration-metadata-upgrade.ipynb
  utils/migration/migration_functions.py
Labels: Topic: Back-end ⚙️, Topic: Front-end 🎨
